/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-02-11 03:15:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.homepage;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class homepage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"homepage.css\">\r\n");
      out.write("\r\n");
      out.write("    <title>AIKYAM</title>\r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body style=\"background-color: #000000;\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <nav class=\"navbar\">\r\n");
      out.write("        <div class=\"logo\">\r\n");
      out.write("            <img src=\"aikyamlogo.png\" alt=\"logo\" class=\"aiklogo\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col2\">\r\n");
      out.write("            <form action=\"\">\r\n");
      out.write("            <input type=\"text\" placeholder=\"Ask your doubt \" class=\"searchbar\">\r\n");
      out.write("            </form>\r\n");
      out.write("            <button type=\"submit\" class=\"submits\"><b>Ask</b></button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"navbar-menu\">\r\n");
      out.write("            <a href=\"#jobs\">Home</a>\r\n");
      out.write("            <a href=\"#companies\">Gurukul</a>\r\n");
      out.write("            <a href=\"3twstimoni\">Avsar</a>\r\n");
      out.write("            <a href=\"#blogs\">About us</a>\r\n");
      out.write("            <a href=\"#\">SignIn</a>\r\n");
      out.write("         <a class=\"nav-link py-3 px-0 px-Lg-3 rounded\" href=\"./login.jsp\">");
      out.print(session.getAttribute("username") );
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"all\">\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("    <div class=\"container7\">\r\n");
      out.write("     \r\n");
      out.write("         \r\n");
      out.write("         <img src=\"colleges.png\" alt=\"Aikyam\" height=\"250\" class=\"right\">\r\n");
      out.write(" \r\n");
      out.write("         <h4 class=\"heading1\"  >connect your colleagues, classmates, and friends on AIKYAM.</h4>\r\n");
      out.write("        \r\n");
      out.write("     \r\n");
      out.write(" </div>\r\n");
      out.write(" </div>\r\n");
      out.write(" <br>\r\n");
      out.write(" <div class=\"card\">\r\n");
      out.write(" <div class=\"container7\" >\r\n");
      out.write("        \r\n");
      out.write("           <img src=\"prof.png\" alt=\"Aikyam\" height=\"250\" class=\"left\">\r\n");
      out.write("           \r\n");
      out.write(" \r\n");
      out.write("         <h4 class=\"heading2\">Who is AIKYAM for?\r\n");
      out.write("             Anyone looking to navigate their professional life.</h4>   \r\n");
      out.write("     </div>\r\n");
      out.write(" </div>\r\n");
      out.write(" <br>\r\n");
      out.write(" <div class=\"card\">\r\n");
      out.write("  <div class=\"container7\">\r\n");
      out.write("       \r\n");
      out.write("    \r\n");
      out.write("         <img src=\"connect.png\" alt=\"Aikyam\" height=\"250\" class=\"right\">\r\n");
      out.write("         <h4 class=\"heading1\">Connect with people who can help</h4>    \r\n");
      out.write("      \r\n");
      out.write(" </div>\r\n");
      out.write(" </div>\r\n");
      out.write(" <br>\r\n");
      out.write(" \r\n");
      out.write(" <div class=\"card\">\r\n");
      out.write(" <div class=\"container7\">\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("     <img src=\"internship.png\" alt=\"Aikyam\" height=\"250\" class=\"left\">\r\n");
      out.write(" \r\n");
      out.write("         <h4 class=\"heading2\">Find the right job or internship for you</h4> \r\n");
      out.write("         \r\n");
      out.write("     \r\n");
      out.write(" </div>\r\n");
      out.write(" \r\n");
      out.write(" </div>\r\n");
      out.write(" <br>\r\n");
      out.write(" <div class=\"card\">\r\n");
      out.write(" <div class=\"container7\">\r\n");
      out.write(" \r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("         <img src=\"community.png\" alt=\"Aikyam\" height=\"250\" class=\"right\">\r\n");
      out.write(" \r\n");
      out.write("         <h4 class=\"heading1\">connect with the community</h4>   \r\n");
      out.write("        \r\n");
      out.write(" </div>\r\n");
      out.write(" </div>\r\n");
      out.write(" <br>\r\n");
      out.write(" \r\n");
      out.write(" <div class=\"card\">\r\n");
      out.write(" <div class=\"container7\">\r\n");
      out.write("     <img src=\"skills.png\" alt=\"Aikyam\" height=\"250\" class=\"left\" >\r\n");
      out.write("         <h4 class=\"heading2\">Learn the skills you need to succeed</h4>\r\n");
      out.write("  \r\n");
      out.write("     \r\n");
      out.write(" </div>\r\n");
      out.write(" </div>   \r\n");
      out.write(" <br>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" <div class=\"card\">\r\n");
      out.write(" <div class=\"container7\">\r\n");
      out.write(" \r\n");
      out.write("     <img src=\"course.png\" alt=\"Aikyam\" height=\"250\" class=\"right\">\r\n");
      out.write("         <h4 class=\"heading1\">Find the right course for you</h4>\r\n");
      out.write("       \r\n");
      out.write(" </div>\r\n");
      out.write(" </div>\r\n");
      out.write(" <br>\r\n");
      out.write(" <div class=\"card\">\r\n");
      out.write(" <div class=\"container7\">\r\n");
      out.write(" \r\n");
      out.write("     <img src=\"proveskills.png\" alt=\"Aikyam\" height=\"250\" class=\"left\">\r\n");
      out.write("         <h4 class=\"heading2\">Prove your skills</h4>\r\n");
      out.write("         \r\n");
      out.write("     </div>\r\n");
      out.write(" </div>\r\n");
      out.write(" \r\n");
      out.write(" <br>\r\n");
      out.write("            \r\n");
      out.write(" \r\n");
      out.write(" <div class=\"card\">\r\n");
      out.write(" <div class=\"container7\">\r\n");
      out.write(" \r\n");
      out.write("         <img src=\"ontime .png\" alt=\"Aikyam\" height=\"250\" class=\"right\">\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("         <h4 class=\"heading1\">Learn on your time</h4>\r\n");
      out.write("     \r\n");
      out.write("     </div>\r\n");
      out.write(" </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
