/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-02-09 17:45:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Aikyam Login</title>\r\n");
      out.write("    <link rel=\"icon\" href=\"./signup/favicon.ico\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./signup/styles.css\">  \r\n");
      out.write("    <!-- <script type=\"text/javascript\">\r\n");
      out.write("     function validate(){\r\n");
      out.write("        var status=document.getElementById(\"status\").value;\r\n");
      out.write("    if(status==\"success\")\r\n");
      out.write("    {\r\n");
      out.write("        alert(\"Congrats, You are now the member of Aikyam\");\r\n");
      out.write("    }\r\n");
      out.write("    if(status==\"invalidname\")\r\n");
      out.write("    {\r\n");
      out.write("        alert(\"Please Enter Your Name\");\r\n");
      out.write("    }\r\n");
      out.write("    if(status==\"invalidemail\")\r\n");
      out.write("    {\r\n");
      out.write("        alert(\"Please Enter Your email\");\r\n");
      out.write("    }\r\n");
      out.write("    if(status==\"invalidpwd\")\r\n");
      out.write("    {\r\n");
      out.write("        alert(\"Please Enter Your Password\");\r\n");
      out.write("    }\r\n");
      out.write("    if(status==\"invalidmobile\")\r\n");
      out.write("    {\r\n");
      out.write("        alert(\"Please Enter Your Mobile\");\r\n");
      out.write("    }\r\n");
      out.write("    if(status==\"invalidmobilelength\")\r\n");
      out.write("    {\r\n");
      out.write("        alert(\"Please Enter Valid Mobile Number\");\r\n");
      out.write("    }\r\n");
      out.write("    if(status==\"invalidrpwd\")\r\n");
      out.write("    {\r\n");
      out.write("        alert(\"Password do not match\");\r\n");
      out.write("    }\r\n");
      out.write("     }\r\n");
      out.write("</script>  -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<input type=\"hidden\" id=\"status\" value=\"");
      out.print(request.getAttribute("status"));
      out.write("\">\r\n");
      out.write("    <div class = \"hero\">\r\n");
      out.write("    <img src=\"./signup/AikyamLogo.png\" alt=\"Aikyam\" class=\"Aikyam\">\r\n");
      out.write("    <div class=\"form\">\r\n");
      out.write("    <form method=\"post\" action=\"RegistrationServlet\" class=\"box\">\r\n");
      out.write("        <input type=\"text\" name=\"username\" placeholder=\"Enter Full Name\" id=\"username\" required=\"required\">\r\n");
      out.write("        <input type=\"email\" name=\"uemail\" placeholder=\"Enter Gmail\" id=\"uemail\" required=\"required\">\r\n");
      out.write("        <input type=\"password\" name=\"password\" placeholder=\"Enter password\" id=\"password\" required=\"required\">\r\n");
      out.write("        <input type=\"password\" name=\"rpassword\" placeholder=\"Repeat password\" id=\"rpassword\" required=\"required\">\r\n");
      out.write("        <input type=\"number\" name=\"umobile\" placeholder=\"Enter mobile number\" id=\"umobile\" required=\"required\"> \r\n");
      out.write("        <input type=\"submit\" name=\"signup\" value=\"signup\" onclick=\"validate()\"/>\r\n");
      out.write("        </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        <p class=\"signup\">Already have a account?<a href=\"login.jsp\" style=\"color: #ff0000;\"> Log In </a></p>\r\n");
      out.write("    </div>\r\n");
      out.write("   <script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"alert/dist/sweetalert.css\">\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    var status = document.getElementById(\"status\").value;\r\n");
      out.write("    if(status==\"success\"){\r\n");
      out.write("    	swal(\"Congrats\",\"You are now the member of Aikyam\",\"success\");\r\n");
      out.write("    }\r\n");
      out.write("    if(status==\"invalidname\"){\r\n");
      out.write("    	swal(\"Failed\",\"Please Enter Your Name\",\"error\");\r\n");
      out.write("    }\r\n");
      out.write("    if(status==\"invalidemail\"){\r\n");
      out.write("    	swal(\"Failed\",\"Please Enter Your email\",\"error\");\r\n");
      out.write("    }\r\n");
      out.write("    if(status==\"invalidpwd\"){\r\n");
      out.write("    	swal(\"Failed\",\"Please Enter Your Password\",\"error\");\r\n");
      out.write("    }\r\n");
      out.write("  \r\n");
      out.write("    if(status==\"invalidmobile\"){\r\n");
      out.write("    	swal(\"Failed\",\"Please Enter Your Mobile\",\"error\");\r\n");
      out.write("    }\r\n");
      out.write("    if(status==\"invalidmobilelength\"){\r\n");
      out.write("    	swal(\"Failed\",\"Please Enter Valid Mobile Number\",\"error\");\r\n");
      out.write("    }\r\n");
      out.write("    if(status==\"invalidrpwd\"){\r\n");
      out.write("    	swal(\"Failed\",\"Password do not match\",\"error\");\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
