/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-02-09 18:30:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.AVSARA;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;

public final class adminjobseekerprofile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<link rel=\"stylesheet\" href=\"styles.css\" type=\"text/css\"/>\n");
      out.write("<title> Admin  JobSeeker Profile </title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\n");
      out.write("<h1>Administrator</h1>\n");
 
String username=(String)session.getAttribute("username");
String usertype=(String)session.getAttribute("usertype");
if(username==null || usertype!="admin") //to check user is logged in, if user is not logged username will be null and page will redirect to index.jsp
{
	 response.sendRedirect("index.jsp");
}

      out.write("\n");
      out.write("<p style=\"text-align:right;\"> Welcome ");
      out.print(username );
      out.write("    <a href=\"logout.jsp\"> Logout </a></p>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "adminmenu.jsp", out, false);
      out.write("\n");
      out.write("<fieldset>\n");
      out.write("<legend>Profile Details</legend>\n");

String user=request.getParameter("user");

Connection con=null;
Statement stmt=null;
ResultSet rs=null;

 Class.forName("com.mysql.jdbc.Driver");
 String url="jdbc:mysql://localhost:3306/ojp";

 con=DriverManager.getConnection(url,"root","");
 stmt=con.createStatement();
 
 rs=stmt.executeQuery("select * from jobseekerprofile where username='"+user+"'");
 while(rs.next())
 {

      out.write("\n");
      out.write("<table width=30%>\n");
      out.write("<th>\n");
      out.write("<td>Basic Details</td>\n");
      out.write("</th>\n");
      out.write("<tr>\n");
      out.write("<td>Name</td>\n");
      out.write("<td>");
      out.print(rs.getString("FNAME") );
      out.write(' ');
      out.print(rs.getString("LNAME") );
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("<td>Designation</td>\n");
      out.write("<td>");
      out.print(rs.getString("DESIGNATION") );
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("<td>Location</td>\n");
      out.write("<td>");
      out.print(rs.getString("LOCATION") );
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("<td>Experience</td>\n");
      out.write("<td>");
      out.print(rs.getString("EXPERIENCE") );
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("<th>\n");
      out.write("<td>Contact Details</td>\n");
      out.write("</th>\n");
      out.write("<tr>\n");
      out.write("<td>Email</td>\n");
      out.write("<td>");
      out.print(rs.getString("EMAIL") );
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("<td>Mobile</td>\n");
      out.write("<td>");
      out.print(rs.getString("MOBILE") );
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("<th>\n");
      out.write("<td>Key Skills</td>\n");
      out.write("</th>\n");
      out.write("<tr align=center>\n");
      out.write("<td colspan=2>");
      out.print(rs.getString("KEYSKILLS") );
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("<th>\n");
      out.write("<td>Projects</td>\n");
      out.write("</th>\n");
      out.write("<tr align=center>\n");
      out.write("<td colspan=2>");
      out.print(rs.getString("PROJECTS") );
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("<th>\n");
      out.write("<td>IT Skills</td>\n");
      out.write("</th>\n");
      out.write("<tr align=center>\n");
      out.write("<td colspan=2>");
      out.print(rs.getString("ITSKILLS") );
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("<th>\n");
      out.write("<td>Education</td>\n");
      out.write("</th>\n");
      out.write("<tr align=center>\n");
      out.write("<td colspan=2>");
      out.print(rs.getString("EDUCATION") );
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("<th>\n");
      out.write("<td>Certifications</td>\n");
      out.write("</th>\n");
      out.write("<tr align=center>\n");
      out.write("<td colspan=2>");
      out.print(rs.getString("CERTIFICATIONS") );
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("<th>\n");
      out.write("<td>Work Details</td>\n");
      out.write("</th>\n");
      out.write("<tr align=center>\n");
      out.write("<td colspan=2>");
      out.print(rs.getString("WORKDETAILS") );
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("<th>\n");
      out.write("<td>Basic Details</td>\n");
      out.write("</th>\n");
      out.write("<tr>\n");
      out.write("<td>DOB</td>\n");
      out.write("<td>");
      out.print(rs.getString("DOB") );
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("<td>Gender</td>\n");
      out.write("<td>");
      out.print(rs.getString("GENDER") );
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("<td>Hometown</td>\n");
      out.write("<td>");
      out.print(rs.getString("HOMETOWN") );
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("<td>PIN</td>\n");
      out.write("<td>");
      out.print(rs.getString("PIN") );
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("<td>Maritial Status</td>\n");
      out.write("<td>");
      out.print(rs.getString("MARITIALSTATUS") );
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("<td>Languages Known</td>\n");
      out.write("<td>");
      out.print(rs.getString("LANGUAGESKNOWN") );
      out.write("</td>\n");
      out.write("</tr>\n");

 }
 rs.close();
 stmt.close();
 con.close();
 
      out.write("\n");
      out.write("</table>\n");
      out.write("</fieldset>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
